language: python

os: linux

jobs:
  include:
  - dist: jammy
    python: 3.10

install:
  - virtualenv env --python=python3
  - source env/bin/activate
  - pip install -r requirements-3-10.txt
  # Python3 needs root and setuid to allow test_kernel to add routes to the kernel
  - sudo chown root env/bin/python3
  - sudo chmod u+s env/bin/python3
  # Insert list of interfaces and their addresses in log
  - ifconfig

script:
  - pytest --cov=rift tests || tools/summarize-test-errors.sh
  - echo "lint rift" && pylint rift
  - echo "lint tests" && pylint tests
  - echo "lint tools" && pylint tools
  - echo "check cli docs" && tools/update_cli_docs.py -c
  - sudo tools/chaos-test-suite --new-venv --iterations 3 && tools/interface_stats.py
  
after_success:
  - codecov
