#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
import sys
from .ttypes import *
default_bandwidth = 100
leaf_level = 0
default_level = 0
default_superspine_level = 24
default_pod = 0
undefined_linkid = 0
default_distance = 1
infinite_distance = 2147483647
invalid_distance = 0
overload_default = False
flood_reduction_default = True
default_lie_holdtime = 3
default_ztp_holdtime = 1
default_not_a_ztp_offer = False
default_you_are_flood_repeater = True
IllegalSystemID = 0
empty_set_of_nodeids = set((
))
default_lie_udp_port = 911
default_tie_udp_flood_port = 912
default_mtu_size = 1400
