#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
import sys
from .ttypes import *
undefined_packet_number = 0
top_of_fabric_level = 24
default_bandwidth = 100
leaf_level = 0
default_level = 0
default_pod = 0
undefined_linkid = 0
default_distance = 1
infinite_distance = 2147483647
invalid_distance = 0
overload_default = False
flood_reduction_default = True
default_lie_holdtime = 3
default_ztp_holdtime = 1
default_not_a_ztp_offer = False
default_you_are_flood_repeater = True
IllegalSystemID = 0
empty_set_of_nodeids = set((
))
default_lifetime = 604800
purge_lifetime = 300
rounddown_lifetime_interval = 60
lifetime_diff2ignore = 400
default_lie_udp_port = 911
default_tie_udp_flood_port = 912
default_mtu_size = 1400
bfd_default = True
undefined_nonce = 0
maximum_valid_nonce_delta = 5
