#!/bin/bash

# Make sure we are running in a virtual environment so that all the pytools work
if [[ -z "${VIRTUAL_ENV}" ]]; then
  echo "Virtual environment not activated"
  exit 1
fi

# Clean up temporary files
cd ${VIRTUAL_ENV}/..
rm -f .coverage.*
rm -f rift.log
rm -f rift.log.html
rm -f rift_expect.log
rm -f log_expect.log
rm -rf interop-results-*